- src/swsssdk/interface.py
Previously database connector subscribed on key notifications, but didn't read messages from publisher until there was no any issue with reading data values. So output queues for clients which use this library was getting bigger and bigger until redis closed data connection.
With this patch I subscribe on key changes only when we waiting for data.
It works in following way:
1. Getting no data exception.
2. Subscribe to key updates
3. Retry request
4. if getting the error again, blocking and waiting for updates.
5. if there're updates, retry request
6. if there're no updates reraise exception
7. after this unsubscribe from key updates
8. and return the data to requestor.
Previously there was error, if there no data, forever, the request would have been performed for ever.
> Fix memory leak. Subscribe on key changes only when we need it

- src/swsssdk/configdb.py
When host cfgdb enforcer daemon starts as a system service, it need to retry the connection before the database service starts successfully.
> Add attribute retry_on for configdb connection

- src/swsssdk/configdb.py
1. Use `|` instead of `:` for separator in redis key, and support hierarchical multiple keys.
2. Support object with no attribute (`data == {}`) with a `"NULL": "NULL"` placeholder. 
3. `set_entry` now support delete entry with `data == None`.
> Support hierarchical keys

- src/swsssdk/port_util.py
The port-mapping functionality is common for SNMP and FDB show CLI implementation. Moving this functionality currently in SNMP module to common library so that this can be reused by both the components.
> Common utility functions for bridge/port mapping

- src/swsssdk/port_util.py
This will prevent snmp subagent from crashing when iterating an empty bridge port map
Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>
> [port_util]: Return empty dictionary instead of a NoneType in get_bridge_port_map

- src/swsssdk/port_util.py
With a recent change in COUNTERS_DB, the SAI OIDs are prefixed with "oid:0x". However, the current scripts/utils are indexing this using key without this prefix. 
Changing to reflect the mapping as before.
> Remove prefix "oid:0x" from sai oid

- src/swsssdk/interface.py
- This is only a workaround solution. The next step is to
remove the hardcoded time frame so that it won't crash
even if the swss is not running.
> [interface]: Extend the max data wait time to 60s

- src/swsssdk/configdb.py
The class ConfigDBConnector has no method to remove the column_key of table entry.  To support it, the method "set_entry" is modified to delete the column_key which value is None.
> Add support to remove the key of table entry

- src/swsssdk/configdb.py
Reverts Azure/sonic-py-swsssdk#15
> Revert "Add support to remove the key of table entry"

- src/swsssdk/configdb.py
Current implementation doesn't remove unwanted columes with set_entry
like below.
```
>>> set_entry('table', 'key', {'key1': 'value1', 'key2': 'value2'})
>>> set_entry('table', 'key', {'key1': 'value3'})
>>> get_entry('table', 'key')
{'key1': 'value3', 'key2': 'value2'}
```
This commit fix this bug.
Signed-off-by: Wataru Ishida <ishida.wataru@lab.ntt.co.jp>
> [configdb] fix bug of leaving unwanted columns in a hash

- src/swsssdk/configdb.py
mod_entry will not delete extra data in the db.
change the set_config to mod_config so that mod_config does not
delete extra data in the db
> [configdb]: add mod_entry, rename set_config to mod_config

- src/swsssdk/configdb.py
Decode data from redis DB into UTF-8 in python3.
> [configdb]: Adopt get_table method to work with python3.

- src/swsssdk/interface.py
to implement a clear fdb cli,  need to send notifications from sonic-utilities to syncd via some channel ASIC_DB, so add an publish interface for the DBInterface.
cli design doc see [https://github.com/Azure/SONiC/wiki/SONiC-Clear-FDB-CLI-Design](url)
> [DBInterface]add publish interface for DBInterface

- src/swsssdk/port_util.py
With _bvid_, the Vlan id is a attribute in SAI_OBJECT_TYPE_VLAN. The API is to return the Vlan Id given a bvid.
> Get Vlan Id from BVID object

- src/swsssdk/interface.py
Add two new methods expire() and exists() for DBInterface class.
expire() can set a timeout to a key
exists() can check whether a key is in the DB
> [DBInterface] add new methods expire() and exists()

- src/swsssdk/port_util.py
Define base indexes for ethernet and portchannel as enum,
so we can avoid magic numbers.
> [port_util] define base indexes for ethernet and portchannel as enum

- src/swsssdk/port_util.py
Fixes issue https://github.com/Azure/SONiC/issues/254
- Avoid import error on python2
- Keep the class with named constants for all the places it is already used 
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
> [port_util] Do not use Enum, for python2 compatibility

- src/swsssdk/configdb.py
Py-redis library starting from 3.00 introduce a behavior change that if objects other than str to be passed as argument to redis, they will not be converted to string, instead an exception will be raised. This breaks the compatibility with our library. This change is to force string conversion in our side to fix the issue.
> Force key/value convertion to str before send to redis lib

- setup.py
So we use specific stable version instead of latest one.
This is to partially fix https://github.com/Azure/sonic-utilities/issues/379
> Fix redis-py version to 2.10.6

- src/swsssdk/configdb.py
commit 9b078292ff8018b7006507b921209d0eb3d03722 (HEAD -> TypeErrorWithPy3k, origin/TypeErrorWithPy3k)
Author: madhu Pal <madhupa@aviznetworks.com>
Date:   Fri Jan 18 05:37:29 2019 +0000
[configdb]: Fixed TypeErrorException when get_config with python3 #44
**What I did**
Fixed TypeError Exception in configdb.py/get_config() API
**How I did**
Fixed by adding PY3K check.
**How to Verify**
root@sonic:~# python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
import swsssdk
db = swsssdk.ConfigDBConnector()
db.connect()
cfg = db.get_config()
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python3.5/dist-packages/swsssdk-2.0.1-py3.5.egg/swsssdk/configdb.py", line 284, …
> [configdb]: Fixed TypeErrorException when get_config with python3 #44

- src/swsssdk/config/database.json
- src/swsssdk/configdb.py
Present code, hard codes the script to access Config-DB only. With this, this class can be used to read any DB. Added a get_keys method, so entire table need not be read into memory, but fetch values as and when needed.
> Enhance SDK to read from any DB by name

- setup.py
- src/swsssdk/dbconnector.py
- src/swsssdk/scripts/sonic-db-cli
* add sonic-db-cli wrapper to replace redis-cli later when applying multiDB
- sonic-db-cli CONFIG_DB keys *   =   redis-cli -p 6379 -n 4 keys * 
* package in swsssdk, it will be installed in /usr/local/bin/sonic-db-cli when swsssdk pkg is installed 
- cover both host and docker environment
admin@ASW-7005:~$ sonic-db-cli LOGLEVEL_Dx
More than three arguments are required. 'usage: sonic-db-cli 'dbname' 'redis commands''
admin@ASW-7005:~$ sonic-db-cli LOGLEVEL_DB x
(error) ERR unknown command `x`, with args beginning with: 
admin@ASW-7005:~$ sonic-db-cli LOGLEVEL_DB1 keys *
Invalid database name input : 'LOGLEVEL_DB1'
admin@ASW-7005:~$ sonic-db-cli LOGLEVEL_DB keys *
1) "SAI_API_IPMC_GROUP:SAI_API_IPMC_GROUP"
2) "SAI_API_VLAN:SAI_API_VLAN"
3) "SAI_API_LAG:SAI_API_LAG"
4) …
> [multi-DB] Part 4: add sonic-db-cli to replace redis-cli

- src/swsssdk/port_util.py
A new COUNTERS_LAG_NAME_MAP table has been added in COUNTERS_DB to keep the portchannel OID to name mapping. This change is to read the portchannel name from this table to display in 'show mac' command when a mac is learnt on a portchannel.
> read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB

- src/swsssdk/port_util.py
Reverts Azure/sonic-py-swsssdk#51 because sonic-snmpagent unit test broken.
> Revert "read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB"

- src/swsssdk/scripts/sonic-db-cli
* When field value is empty:
* today redis-cli return "", sonic-db-cli return 'None'
* some caller check 'None' word since the data may be string 'None' 
* CHANGES, sonic-db-cli check return type , if it is None, then return "", if not None, return the string (including "None")
* when return value is a list:
* today redis-cli returns "TB|E1 TB|E2 TB|E3 ..." , sonic-db-cli returns "['TB|E1',  'TB|E2',  'TB|E3'] ..", when list is empty, redis-cli return "" while sonic-db-cli returns [].
* CHANGES, sonic-db-cli check return type, it it is a list, output all thge element as a joint string.
* So far, only found these two usage is needed to be changed in sonic-db-cli , other redis operation like SET/FLUSH/GET/HGET/KEYS are good and the output are some format after these changes.
Signed-off-by: …
> [MultiDB]: update sonic-db-cli output to redis-cli output format

- src/swsssdk/scripts/sonic-db-cli
@qiluo-msft 
* We made a mistake earlier. When we try  `redis-cli keys "XXX"` output earlier, we thought it join KEY by blank, actually it is `\n`. But the output still have issue when KEY contains blank, since for loop in shell script make the KEY contains blank into two parts.
* We should use `\n` to join python list output as well, though there is no effect when shell script iterating each element in a for loop.
```
admin@ASW-7005:~$ echo $(redis-cli -n 4 keys *PortChannel10*)
PortChannel10 Test PORTCHANNEL|PortChannel10 VLAN_MEMBER|Vlan10|PortChannel10 PORTCHANNEL_MEMBER|PortChannel10|Ethernet9
admin@ASW-7005:~$ echo "$(redis-cli -n 4 keys *PortChannel10*)"
PortChannel10 Test
PORTCHANNEL|PortChannel10
VLAN_MEMBER|Vlan10|PortChannel10
PORTCHANNEL_MEMBER|PortChannel10|Ethernet9 …
```
> [MultiDB]: update sonic-db-cli list output seperator to '\n'

- src/swsssdk/configdb.py
sonic-cfggen uses mod_config to write to db. mod_config API should allow
deletion of entire table instead of throwing python exception.
Signed-off-by: Praveen Chaudhary pchaudhary@linkedin.com
Testing: [I tested with YANG model in picture, but that does not matter for this PR]
Before Fix:
```
admin@lnos-x1-a-asw01:~/pc_testing_merge$ cat interface_none.json
{ "INTERFACE": null }
admin@lnos-x1-a-asw01:~/pc_testing_merge$ sudo config load interface_none.json -y
Loaded below Yang Models
['sonic-acl', 'sonic-head', 'sonic-interface', 'sonic-port', 'sonic-portchannel', 'sonic-vlan']
Reading data from interface_none.json
Data Validation successful
Running command: /usr/local/bin/sonic-cfggen -j interface_none.json --write-to-db
Traceback (most recent call last):
File …
```
> [configdb.py]: Allow deletion of entire table from mod_config API.

- src/swsssdk/port_util.py
Add Azure/sonic-py-swsssdk#51 back in by reverting Azure/sonic-py-swsssdk#57, in because issues should be addressed by the merge of https://github.com/Azure/sonic-swss/pull/1124
> Un-revert "read portchannel name from LAG_NAME_MAP_TABLE in COUNTERS_DB"

- src/swsssdk/dbconnector.py
- src/swsssdk/scripts/sonic-db-cli
* ping pong all redis instances using sonic-db-cli PING
* for the first commit of multiDB changes, we introduced script dockers/docker-database/ping_pong_db_insts to ping pong all redis instances instead of redis-cli ping, at that time , swsssdk lib is not modified to support multiDB.
* another PR will replace script ping_pong_db_insts with sonic-db-cli PING
* another PR will add SAVE and FLUSHALL option for sonic-db-cli as well
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
> [MultiDB] add sonic-db-cli PING all instances support

- src/swsssdk/scripts/sonic-db-cli
Fix sonic-db-cli script to be compatible with python3 and python2.7
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
> Fix sonic-db-cli script to be compatible with python3 and python2.7

- src/swsssdk/port_util.py
Add calculation of interface index for backplane interfaces
in multi asic platform. Multiasic platform will have
backplane interface names of the format Ethernet-BP<x>.
Signed-off-by: SuvarnaMeenakshi <sumeenak@microsoft.com>
> [Multiasic]: Add calculation of interface index for backplane interfaces

- src/swsssdk/scripts/sonic-db-cli
* remove Judy's duplicated func for tcp and unix socket, using parameter instead
* add SAVE option to save all redis instances , originally it is used as redis-cli save
* add FLUSHALL option to flush all redis instances, originally it is used as redis-cli flushall
* SUCCESS cases:
```
admin@ASW-7005:~$ sonic-db-cli PING
PONG
admin@ASW-7005:~$ sonic-db-cli SAVE
OK
admin@ASW-7005:~$ sonic-db-cli FLUSHALL
OK
admin@ASW-7005:~$ docker exec -it database bash
root@ASW-7005:/# ls /var/lib/redis*
/var/lib/redis:
dump.rdb
/var/lib/redis1:
dump.rdb
/var/lib/redis2:
dump.rdb
admin@ASW-7005:~$ sonic-db-cli ASIC_DB keys *
admin@ASW-7005:~$ 
```
* FAILED cases:
```
admin@ASW-7005:~$ sonic-db-cli PING
Could not connect to Redis at 127.0.0.1:16379: Connection refused
Could not connect to Redis at …
```
> [MultiDB] add sonic-db-cli SAVE/FLUSHALL option

- src/swsssdk/scripts/sonic-db-cli
Fix https://github.com/Azure/sonic-buildimage/issues/4632
In py3, the response from redis connector is encoded as byte array. They
need to be decoded before accessing them as strings.
Use following commands to test
sonic-db-cli CONFIG_DB "keys *"
sonic-db-cli CONFIG_DB "hget PORT|Ethernet0 admin_status"
Signed-off-by: Rajendra Dendukuri <rajendra.dendukuri@broadcom.com>
> Decode byte encoded response from redis before printing

- src/swsssdk/dbconnector.py
* issue : https://github.com/Azure/sonic-py-swsssdk/issues/72
* the root cause is : SonicV2Connector connect(dbname) calls base class method connect(dbid), while when connection failed and retry, base class try to call self. connect() which is onicV2Connector connect(dbname) since name are the same. It should call its own connect(dbid).
* for multiDB, we use methods from SonicV2Connector instead of DBInterface based on earlier changes
* we should make sure DBInterface class method uses its own methods inside, hence making DBInterface class as a member of SonicV2Connector instead of inheritance
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
> [MultiDB] SonicV2Connector class use DBInterface class as member instead of inheritance

- setup.py
Upgrade outdated redis python library to latest version, which is still supporting python2.
> Upgrade redis library to 3.5.3

- test/config/database_config.json
- test/config/database_global.json
- test/test_moduleLoad.py
Why
-----
Updates to the python module testcases for the namespaces. The changes include
* Add a database_config.json file for the test scripts in test/config directory. 
* Update the name of a test API which was missed out earlier 
* Changes in database_global.json file to test various input formats of database_config.json files like the absolute path, relative path etc.
> Updates to the namespace API's for test_moduleLoad.py

- src/swsssdk/port_util.py
Add 2 new utility functions, to be used by snmpagent.
Related to [#133](https://github.com/Azure/sonic-snmpagent/pull/133)
> [port_util] add get_rif_port_map, get_vlan_interface_oid_map

- src/swsssdk/dbconnector.py
Remove the check to prevent the TCP mode connectivity when the namespace is specified. This is related to PR https://github.com/Azure/sonic-buildimage/pull/4779
> Allowing TCP connections with namespace as well.

- src/swsssdk/configdb.py
Signed-off-by: Danny Allen <daall@microsoft.com>
After debugging w/ Tamer offline we figured out that https://github.com/Azure/sonic-buildimage/issues/5263 was being caused because of this call to `bgsave`.
Essentially what is happening is that the Config DB is being saved/checkpointed to disk when this `bgsave` is called, so when the virtual switch restarts the `/etc/sonic/config_db.json` is being added to the existing contents of config DB rather than overwriting them.
> [configdb] Remove call to "bgsave" from table update

- src/swsssdk/interface.py
* correct wrong connect() parameter
* store and get db_id from local
* del old/unused redis and pubsub obj in array
Signed-off-by: Dong Zhang d.zhang@alibaba-inc.com
> [MultiDB] fix wrong parameter number in interface.py

- src/swsssdk/port_util.py
More context:
We plan to migrate existing SonicV2Connector from `decode_responses=False` (default) to `decode_responses=True`
> Make functions also working for SonicV2Connector with decode_responses=True

- src/swsssdk/configdb.py
`ConfigDBConnector` is not working well under python3, for example:
```
Oct 29 21:56:58.496505 sonic INFO hostcfgd[20662]: Traceback (most recent call last):
Oct 29 21:56:58.496724 sonic INFO hostcfgd[20662]:   File "/usr/bin/hostcfgd", line 387, in <module>
Oct 29 21:56:58.496873 sonic INFO hostcfgd[20662]:     main()
Oct 29 21:56:58.497014 sonic INFO hostcfgd[20662]:   File "/usr/bin/hostcfgd", line 382, in main
Oct 29 21:56:58.497147 sonic INFO hostcfgd[20662]:     daemon = HostConfigDaemon()
Oct 29 21:56:58.497939 sonic INFO hostcfgd[20662]:   File "/usr/bin/hostcfgd", line 237, in __init__
Oct 29 21:56:58.498103 sonic INFO hostcfgd[20662]:     tacacs_server = self.config_db.get_table('TACPLUS_SERVER')
Oct 29 21:56:58.498236 sonic INFO hostcfgd[20662]:   File …
```
> Fix bug: ConfigDBConnector.get_table does not work in python3

- src/swsssdk/dbconnector.py
Following the steps in the plan https://github.com/Azure/sonic-py-swsssdk/pull/89
> [SonicV2Connector] make decode_responses=True as default, so python2 application need no code change when migrated to python3

- src/swsssdk/port_util.py
Otherwise there is an error:
```
TypeError: in method 'FieldValueMap___contains__', argument 2 of type 'std::map< std::string,std::string >::key_type const &'
```
> FieldValueMap `contains`(`in`)  will also work when migrated to libswsscommon (C++ with SWIG wrapper).

- src/swsssdk/configdb.py
The original code was tested in python2, which convert a str to a unicode str. It is working but not needed.
```python
>>> client.hgetall('QUEUE|Ethernet100|1')
{'scheduler': '[SCHEDULER|scheduler.0]'}
>>> client.hgetall(u'QUEUE|Ethernet100|1')
{'scheduler': '[SCHEDULER|scheduler.0]'}
>>> a = {}
>>> a['b'] = 'c'
>>> a[u'b'] = 'cc'
>>> a
{'b': 'cc'}
```
Tested in DUT
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from swsssdk import SonicV2Connector, ConfigDBConnector
>>> cfg = ConfigDBConnector()
>>> cfg.connect()
>>> cfg.get_config()
{'QUEUE': ...
```
```
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more …
```
> Fix: no need to decode() after redis client scan, so it will work for both python2 and python3

- src/swsssdk/port_util.py
Master branch has no such issue.
We found FDB appears on default vlan, and snmpagent will throw exception because default vlan has no SAI_VLAN_ATTR_VLAN_ID attribute
> Workaround Mellanox default vlan has no SAI_VLAN_ATTR_VLAN_ID attribute

- src/swsssdk/port_util.py
Signed-off-by: liora <liora@nvidia.com>
**What I did**
Allow system with no ports in config db to run without errors/warnings. 
This is needed for modular system which should boot and run properly without line cards.
**How I did it**
Check if table exists before calling get_all for it and return empty list if there are no ports in COUNTERS_PORT_NAME_MAP table in counters db.
**How to verify it**
Run snmpwalk on the root oid.
**Important**
This PR must be merged before PR https://github.com/Azure/sonic-snmpagent/pull/221 is merged.
> [port_util] Allow system without ports in config db run without errors

- src/swsssdk/port_util.py
Signed-off-by: liora <liora@nvidia.com>
**What I did**
Change argument 'blocking' in call to function get_all() to a keyword argument as it should.
**How I did it**
Add blocking=xxx in function call.
**How to verify it**
This issue is failing the checkers when updating this submodule hash in sonic-buildimage (see https://github.com/Azure/sonic-buildimage/pull/8696).
> [port_util] Fix issue in function get_interface_oid_map

- src/swsssdk/scripts/sonic-db-cli
During database docker start, when the redis servers are started, ping pong is done to check the server connection status. For server within the card ping pong is done using unix socket. In VOQ chassis, to check the connection to redis server in supervisor card, we need to use host name and port instead of using unix socket.
> [voq][chassis] Fix for issue in chassis redis server connection check

- src/swsssdk/interface.py
In some circumstances calls are made to query the Redis database without checking if a given key (or key/field pair) exists, and with code to handle the case where it does not. For example many show commands query all possible relevant data, without checking if it exists. In these cases it would be useful to be able to prevent warning logs being written for every missing field, and so we add that option in this PR.
> Add option to suppress warnings when querying Redis

- test/test_moduleLoad.py
Fix this issue: https://github.com/sonic-net/sonic-buildimage/issues/12558
UT failed under python2: test_BlockUseSwsssdk()
>       result = subprocess.run(["python", "-c", "import swsssdk;exit()"], capture_output=True, cwd=swsssdk_path)
E       AttributeError: 'module' object has no attribute 'run'
Update UT to use subprocess.check_output(), which support by both python3 and python2.
Pass all UT.
Fix UT test_BlockUseSwsssdk()
> Fix UT test_BlockUseSwsssdk()

- src/swsssdk/config/database_config.json
- src/swsssdk/sonic_db_dump_load.py
- test/config/database_config.json
This PR is part of the following HLD:
Persistent loglevel HLD: https://github.com/sonic-net/SONiC/pull/1041
**- What I did**
Deleted the LOGLEVEL_DB.
After the Logger tables moved from the LOGLEVEL_DB to the CONFIG_DB and the jinja2_cache was deleted the LOGLEVEL_DB is not in use.
**- How I did it**
Removed the LOGLEVEL_DB from the SONiC code
**- How to verify it**
All tests were passed
> Remove LOGLEVEL DB since is no longer used

- src/swsssdk/sonic_db_dump_load.py
- test/sonic_db_dump_load_test.py
**Description**
Replace exit() by sys.exit()
**Motivation and Context**
sys.exit is better than exit, considered good to use in production code.
Ref:
https://stackoverflow.com/questions/6501121/difference-between-exit-and-sys-exit-in-python
https://stackoverflow.com/questions/19747371/python-exit-commands-why-so-many-and-when-should-each-be-used
> replace exit() with sys.exit()

- setup.py
The true versions are specified by Dockerfile, such as dockers/docker-config-engine-bullseye/Dockerfile.j2. It may use later versions, we do not want setup.py to install an older version in that case.
See the PR https://github.com/sonic-net/sonic-py-swsssdk/pull/136
> Loosen the redis version requirement

- test/sonic_db_dump_load_test.py
Submodule update failed for python 2 because mock import statement is not compatible for python 2
Fix import statement for python 2 and python 3
Passed UT for python 2 and python 3
```
platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
rootdir: /sonic/src/sonic-py-swsssdk, inifile: pytest.ini
plugins: cov-2.6.0
collected 7 items
test/sonic_db_dump_load_test.py ..                                                     [ 28%]
test/test_moduleLoad.py ....                                                           [ 85%]
test/test_port_util.py .                                                               [100%]
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0
rootdir: /sonic/src/sonic-py-swsssdk, configfile: pytest.ini
plugins: pyfakefs-5.2.2, …
```
> unittest - fix import for python 2

- .github/workflows/semgrep.yml
- azure-pipelines.yml
Make Semgrep CI same practice with other SONiC repositories
**Why I did it**
[Semgrep](https://github.com/returntocorp/semgrep) is a static analysis tool to find security vulnerabilities.
When opening a PR or commtting to PR, Semgrep performs a diff-aware scanning, which scans changed files in PRs.
When merging PR, Semgrep performs a full scan on master branch and report all findings.
Ref: - [Supported Language](https://semgrep.dev/docs/supported-languages/#language-maturity) - [Semgrep Rules](https://registry.semgrep.dev/rule)
**How I did it**
Integrate Semgrep into this repository by committing a job configuration file
> [actions] Support Semgrep by Github Actions
